services:
  app:
    build: .
    container_name: automacao_bpo_financeiro
    volumes:
      - ./contaazul:/app/contaazul
    env_file:
      - contaazul/secret/.env
    command: >
      uvicorn contaazul.app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
    ports:
      - "8000:8000"
