version: "3.9"

services:
  app:
    build: .
    container_name: automacao_bpo_financeiro
    volumes:
      - ./contaazul:/app/contaazul
    env_file:
      - contaazul/secret/.env
    command: python -m contaazul.app.main

